FROM python:3.13-slim

USER root
WORKDIR /app

COPY . .
RUN python -m pip install Flask paho-mqtt firebase-admin pytz python-dotenv
RUN chmod 777 /app/script.sh

EXPOSE 5000

ENTRYPOINT ["bash", "-c", "/app/script.sh"]
