FROM python:3.13-slim

WORKDIR /app

COPY . .
RUN python -m venv .venv && \
    source .venv/bin/activate && \
    python -m pip install streamlit

EXPOSE 8000

ENTRYPOINT ["streamlit", "run", "--server.port", "8000", "streamlit.py"]
