FROM python:3.13-slim

WORKDIR /app

COPY . .
RUN python -m pip install Flask paho-mqtt firebase-admin pytz python-dotenv &&
    chmod +x /app/script.sh

EXPOSE 5000

ENTRYPOINT ["bash", "-c", "/app/script.sh"]
